
package vista_Calculadora;

import calculadora_tareaII.controller.Impl_Factory;
import calculadora_tareaII.controller.Operaciones_AbstractFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Audias Guevara
 */
public class Calculadora extends javax.swing.JFrame implements ActionListener{

    public Operaciones_AbstractFactory factory;
    
    private double a, b;
    private String operacionSeleccionada;
    
    
    
    
    public Calculadora() {
        initComponents();
        
        this.setLocation(550, 200);
        this.setTitle("MI CALCULADORA");
        this.setResizable(false);
        factory = new Impl_Factory();
        btn_suma.addActionListener(this);
        btn_resta.addActionListener(this);
        btn_multiplicacion.addActionListener(this);
        btn_division.addActionListener(this);
        btn_igual.addActionListener(this);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_suma = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        txt_texto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_division = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_suma.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 50));

        btn_resta.setFont(new java.awt.Font("Tahoma", 1, 58)); // NOI18N
        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 110, 100, 50));

        btn_igual.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn_igual.setText("=");
        getContentPane().add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 246, 101, 55));
        getContentPane().add(txt_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 29, 235, 49));

        jPanel1.setLayout(null);

        btn_division.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_division.setText("/");
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_division);
        btn_division.setBounds(160, 180, 100, 50);

        btn_multiplicacion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_multiplicacion.setText("X");
        jPanel1.add(btn_multiplicacion);
        btn_multiplicacion.setBounds(20, 180, 100, 47);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_restaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_texto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       if (e.getSource() == btn_suma || e.getSource() == btn_resta
                || e.getSource() == btn_multiplicacion || e.getSource() == btn_division) {//CAPTURAR VALOR PARA LA OPERACION
            a = Double.parseDouble(txt_texto.getText());
            txt_texto.setText(""); //LIMPIANDO PARA EL SIGUIENTE VALOR
            operacionSeleccionada = e.getActionCommand(); // GUARDANDO LA OPERACION SELECCIONADA
        } else if (e.getSource() == btn_igual) { //CAPTURANDO EL SIGUIENTE VALOR PARA CALCULAR
            b = Double.parseDouble(txt_texto.getText());
            txt_texto.setText("");
            if (operacionSeleccionada.equals("+")) { // EFECTUANDO LA OPERACION SELECCIONADA
                double resultado = factory.efectuarSuma().calcular(a, b);
                txt_texto.setText(String.valueOf(resultado));
            } else if (operacionSeleccionada.equals("-")) {
                double resultado = factory.efectuarResta().calcular(a, b);
                txt_texto.setText(String.valueOf(resultado));
            } else if (operacionSeleccionada.equals("X")) {
                double resultado = factory.efectuarMultiplicar().calcular(a, b);
                txt_texto.setText(String.valueOf(resultado));
            } else if (operacionSeleccionada.equals("/")) {
                double resultado = factory.efectuarDividir().calcular(a, b);
                txt_texto.setText(String.valueOf(resultado));
            }
        }

    } 
    }

